apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  namespace: mysql-namespace
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: 191779805693.dkr.ecr.us-east-1.amazonaws.com/mysql:latest
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "password"
    - name: MYSQL_DATABASE
      value: "employees"
    ports:
    - containerPort: 3306
  imagePullSecrets:
  - name: ecr-secret
